services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./bomen:/app/bomen
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: "postgres:15.4-alpine"
    env_file: .env
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 5s