apiVersion: v1
data:
  {{ range $path, $_ := .Files.Glob "db-scripts/*" }}
  {{- with $ }} 
  {{ base $path }}: |- 
    {{ range .Files.Lines $path }} 
      {{ . }}{{ end }}
  {{- end }}
  {{ end }}
kind: ConfigMap
metadata:
  name: db-init-scripts