apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: postgres
  name: {{ .Release.Name }}-postgres-env
  namespace: {{ .Release.Namespace }}
data:
  POSTGRES_USER: {{ .Values.config.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.config.postgresPassword }}
  POSTGRES_DB: {{ .Values.config.postgresDatabase  }}
  PGDATA: {{ .Values.config.dataDirMountPath  }}