apiVersion: v1
data:
  {{- $dbScriptsPath := .Values.dbScriptsPath -}}
  {{ range $path, $_ := .Files.Glob "$dbScriptsPath" }}
  {{- with $ }} 
  {{ base $path }}: |- 
    {{ range .Files.Lines $path }} 
      {{ . }}{{ end }}
  {{- end }}
  {{ end }}
kind: ConfigMap
metadata:
  name: db-init-scripts