apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: {{ .Release.Name }}-postgres-headless
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
  - name: postgres-tcp
    port: 5432
    protocol: TCP
    targetPort: postgres-tcp
  selector:
    app: postgres
  type: ClusterIP
status:
  loadBalancer: {}