apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  namespace: {{ .Release.Namepsace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgres-tcp
      protocol: TCP
      name: postgres-tcp
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
